version: '2.3'

services:
  chat-server:
    image: chat:server
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    networks:
      - internal
    ports:
      - 8080:8080
      - 11001:11001 #debug
    environment:
      - JAVA_OPTS=-Xms512m -Xmx2048m -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=11001
    mem_limit: 2048m
    restart: always

  chat-ui:
    image: chat:ui
    build:
      context: ../
      dockerfile: docker/ui/Dockerfile
    networks:
      - internal
    ports:
      - 9090:80

networks:
 internal:
